apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology-ml
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: netology-ml
    spec:
      containers:
        - image: tomcat:8.8.69
          name: tomcat
          ports:
            - containerPort: 8080